openapi: 3.1.0
info:
  title: Gitlab Service
  description: |-
    This service is used by the other services of PulsR platform to interact with an instance of Gitlab.

  contact:
    email: julien.papillon@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
tags:
  - name: group
    description: Manage Gitlab groups
  - name: project
    description: Manage Gitlab projects

paths:
  /group:
    get:
      tags:
        - group
      summary: Retrieve the list of available groups
      description: Retrieve the list of available groups for the PulsR Service Account
      operationId: getAllGroups
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
  /group/{groupId}/subgroups:
    get:
      tags:
        - group
      summary: Retrieve the list of subgroups of a group
      description: Retrieve the list of subgroups of a group
      operationId: getGroupSubgroups
      parameters:
        - name: groupId
          in: path
          description: ID of the parent group
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
  /groups/{groupId}/projects:
    get:
      tags:
        - group
      summary: Retrieve the list of projects of a group
      description: Retrieve the list of projects of a group
      operationId: getGroupProjects
      parameters:
        - name: groupId
          in: path
          description: ID of the parent group
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
        '400':
          description: Invalid ID supplied
        '404':
          description: Group not found
  /project:
    get:
      tags:
        - project
      summary: Retrieve the list of projects
      description: Retrieve the list of projects
      operationId: getProjects
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'
    post:
      tags:
        - project
      summary: Create a new project
      description: Create a new project inside an existing group
      operationId: createProject
      requestBody:
        description: Create a new pet in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Project'
          application/xml:
            schema:
              $ref: '#/components/schemas/Project'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Project'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
            application/xml:
              schema:
                $ref: '#/components/schemas/Project'
        '405':
          description: Invalid input
  /project/{projectId}:
    get:
      tags:
        - project
      summary: Retrieve a single project
      description: Retrieve a single project
      operationId: getProject
      parameters:
        - name: projectId
          in: path
          description: ID of the project
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Project'
            application/xml:
              schema:
                $ref: '#/components/schemas/Project'
        '400':
          description: Invalid ID supplied
        '404':
          description: Project not found
    delete:
      tags:
        - project
      summary: Delete a single project
      description: Delete a single project
      operationId: deleteProject
      parameters:
        - name: projectId
          in: path
          description: ID of the project
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Project not found

components:
  schemas:
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int32
          examples: 
            - 12345
        name:
          type: string
          examples: 
            - mygroup
        path:
          type: string
          examples: 
            - bar
        full_path:
          type: string
          examples: 
            - foo/bar
      xml:
        name: group
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int32
          examples: 
            - 45678
        group_id:
          type: integer
          format: int32
          examples: 
            - 12345
        name:
          type: string
          examples: 
            - myproject
        default_branch:
          type: string
          examples: 
            - main
            - master
        http_url_to_repo:
          type: string
          examples: 
            - http://gitlab.example.com/mygroup/myproject.git
      xml:
        name: project
